### ISSUE TITLE
2023.5 - Unable to import component: cannot import name 'async_get_registry'

### ISSUE THREAD

**Issue by toddstar** [travisghansen/hass-opnsense#82]
After upgrading to 2023.5 (beta) the integration is failing to load with the following logged

```
Logger: homeassistant.setup
Source: setup.py:214
First occurred: 27 April 2023 at 21:15:23 (1 occurrences)
Last logged: 27 April 2023 at 21:15:23

Setup failed for custom integration opnsense: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

**Comment by alexdelprete** [comment]
I included the fix in PR #70 that is waiting to be reviewed by @travisghansen.

**Comment by alexdelprete** [comment]
@toddstar can you please test v0.1.16 and report back? Thanks.

**Comment by toddstar** [comment]
> @toddstar can you please test v0.1.16 and report back? Thanks.

Back working again now thanks 👍
